#配置端口
server:
  port: 80

spring:
  #配置连接
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/vueblog?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
      username: root
      password: 1234
  #配置邮箱信息
  mail:
    host: smtp.qq.com
    username: 1730570670@qq.com
    password: ibowmojjpyejchda
    default-encoding: UTF-8
  activemq:
    pool:
      enabled: true
#配置MyBatisPlus环境
mybatis-plus:
  #配置mapper接口地址
  mapper-locations: classpath:/mapper/**/*.xml
  #全局配置
  configuration:
    #配置日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    #配置允许驼峰
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      id-type: assign_id
      #过滤前缀
      table-prefix: blog_
  #给实体包命名
  type-aliases-package: com.blog.vuemanger.pojo
#自定义发送邮箱地址(发送者)
vuemanger:
  emailfrom: 1730570670@qq.com

tencent:
  #腾讯云存储所需信息
  cloud:
    #SecretId
    accessKey: AKIDa0A3f05tQhiSv72g39yXppY1EAoGRL4Y
    #SecretKey
    secretKey: JL6ZlgKhofEWXHkwrWv3uVoqa3GCrFMD
    #所属区域
    bucket: ap-guangzhou
    #存储桶名称
    bucketName: hjy-1309140759
    #访问域名
    path: https://hjy-1309140759.cos.ap-guangzhou.myqcloud.com
    #路径前缀
    prefix: hjy
